### ISSUE TITLE
Inheriting classes seems not to be found as items for import

### ISSUE THREAD

**Issue by jmp75** [asmeurer/removestar#17]
First: very nifty utility, thank you.

I came across a possible issue with removestar 1.2.2

a submodule forecast.py has 

```py
class ForecastInputs(ForecastTimeline):
```
but running removestar on another module importing it:

```text
Error with reporting.py: Error importing waa.forecast: name 'ForecastInputs' is not defined
```

I'll see if I can figure out a fix and submit a pull request.

**Comment by asmeurer** [comment]
Interesting. removestar uses pyflakes to find missing names, so it's possible there is a bug there. Aso make sure you have the latest version of pyflakes installed.

**Comment by asmeurer** [comment]
Can you clarify what the imports and the relevant code in each module looks like? Were they absolute or relative imports? I am not able to reproduce this issue. 

The error seems to indicate that `from waa.forcast import *` fails. Can you confirm that this works?

**Comment by jmp75** [comment]
I cannot reproduce this issue anymore, and had not stashed or commited changes at the time (should have).

I had done a few sanity checks before submitting the issue but must have missed something. If I try now to insert a syntactic error into `forecast.py` I get `Error with reporting.py: Error importing waa.forecast: invalid syntax (forecast.py, line 1132)` which is not the error message I had observed, and I am sure the class definition would have been there. 

I still have the trace from my console below, in case this helps someone diagnose a similar issue down the track. I was gradually uncommenting `from waa.blah import *` lines in `reporting.py` to avoid indirect imports.

```text
....
Warning: reporting.py: could not find import for 'INDX_CST_PARA_JC'
Warning: reporting.py: could not find import for 'provincial_share'
## uncommenting `from waa.deriveddata import *` in reporting.py, which has INDX_CST_PARA_JC 
$>:~/path/to/pkgs/waatool/waa$ removestar -i reporting.py 
Warning: reporting.py: could not find import for 'ForecastInputs'
Warning: reporting.py: could not find import for 'provincial_share'
## Then after uncommenting `from waa.forecast import *` in reporting.py:
$>:~/path/to/pkgs/waatool/waa$ removestar -i reporting.py 
Error with reporting.py: Error importing waa.forecast: name 'ForecastInputs' is not defined
```
