### ISSUE TITLE
Support noqa comments

### ISSUE THREAD

**Issue by asmeurer** [asmeurer/removestar#20]
See https://github.com/asmeurer/removestar/pull/19

Even if we don't support noqa, we should also fix the regex to match star import lines that end in a comment.

**Comment by h4l** [comment]
For reference, here is Flake8's regex for noqa comments: https://github.com/PyCQA/flake8/blob/9815f49cc48dec39977ca4954beb833ba489f969/src/flake8/defaults.py#L27

**Comment by h4l** [comment]
I'd be happy to implement this if you like. 

As well as `# noqa: F403` ("‘from module import *’ used; unable to detect undefined names") there's also `F401` ("module imported but unused"), which can also apply to a star import. Do you think the behaviour should be to leave star imports that are marked with either of those?

**Comment by asmeurer** [comment]
Sure go ahead. I hadn't planned on doing it. 

I'm not sure F401 would apply to a star import. Can you confirm that? It seems to me it would only apply to `import x` where `x` is unused. `from x import *` does not import the name `x` so it doesn't seem like it would apply.

**Comment by h4l** [comment]
OK cool, will do.

F401 can indeed apply to star imports. But seemingly only when nothing from the star import could be used (e.g. in b.py here it's not used):

a.py
```python
from abc import *
```

b.py
```python
from abc import *
from base64 import *


FOO = b64encode('bar')
```

c.py:
```python
from abc import *
from base64 import *
```

d.py:
```python
from abc import *
from base64 import *

FOO = list()
```

```console
$ flake8 *.py
a.py:1:1: F403 'from abc import *' used; unable to detect undefined names
a.py:1:1: F401 'abc.*' imported but unused
b.py:1:1: F403 'from abc import *' used; unable to detect undefined names
b.py:2:1: F403 'from base64 import *' used; unable to detect undefined names
b.py:5:7: F405 'b64encode' may be undefined, or defined from star imports: abc, base64
c.py:1:1: F403 'from abc import *' used; unable to detect undefined names
c.py:1:1: F401 'abc.*' imported but unused
c.py:2:1: F403 'from base64 import *' used; unable to detect undefined names
c.py:2:1: F401 'base64.*' imported but unused
d.py:1:1: F403 'from abc import *' used; unable to detect undefined names
d.py:1:1: F401 'abc.*' imported but unused
d.py:2:1: F403 'from base64 import *' used; unable to detect undefined names
d.py:2:1: F401 'base64.*' imported but unused
```
