### ISSUE TITLE
Not listed at https://pre-commit.com/hooks.html ?

### ISSUE THREAD

**Issue by gmseb** [asmeurer/removestar#58]
Hi @asmeurer, thanks for this helpful tool!

I noticed its not listed at https://pre-commit.com/hooks.html . Are there plans to add it or reasons to keep it off that list?

Best, Sebastian

**Comment by Saransh-cpp** [comment]
HI @gmseb,

Thanks for opening this issue. I am afraid that they have updated the submission conditions to their page -

> the previous iteration of this page was a laundry list of hooks and maintaining quality of the listed tools was cumbersome.
>
> this page is not intended to be exhaustive
>
> you may send [a pull request](https://github.com/pre-commit/pre-commit.com/blob/main/sections/hooks.md) to expand this list however there are a few requirements you must follow or your PR will be closed without comment:
> 
> - the tool must already be fairly popular (>500 stars)
> - the tool must use a managed language (no system / script / docker hooks)
> - the tool must operate on files

Unfortunately, we don't have >500 stars :(
